const query=document.getElementById('query'), matches=document.getElementById('matches'),detail=document.getElementById('detail');
let selected=null,choice='C';
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function search(q){let words=norm(q).split(' ').filter(Boolean);return CENTERS.filter(c=>words.every(w=>norm(c.name+' '+c.town+' '+(c.code||'')).includes(w))).sort((a,b)=>a.name.localeCompare(b.name,'es'));}
function results(){const list=search(query.value);document.getElementById('count').textContent=list.length+' centros encontrados';matches.innerHTML='';if(!list.length){matches.innerHTML='<p>No hay coincidencias. Prueba con parte del nombre. Comprueba el nombre o el código de ocho dígitos.</p>';return;}for(const c of list){let b=document.createElement('button');b.className='match';b.setAttribute('aria-pressed',String(c.id===selected));b.innerHTML='<strong>'+esc(c.name)+'</strong><small>'+esc(c.town)+' · '+esc(c.code)+'</small>';b.onclick=()=>select(c.id);matches.append(b);}}
function select(id){selected=id;choice='C';render();results();}
function render(){const c=CENTERS.find(c=>c.id===selected);if(!c)return;let participating=c.participates==='SÍ';let canImprove=!participating&&Number(c.level)>=1&&Number(c.level)<5;let voluntaryB=canImprove&&choice==='B';let m=voluntaryB?'B':c.mode==='B/C'?choice:c.mode;let applying=participating||voluntaryB;let title=participating?'Sí, corresponde participar para mantener la certificación':'No tiene que participar obligatoriamente este curso';let why=participating?'El listado provincial marca «SÍ» y asigna la modalidad '+c.mode+'.':'El listado provincial marca «NO» y no asigna modalidad para 2026/2027.';let explanation=m==='A'?'Corresponde realizar el proceso de certificación por modalidad A. La fecha exacta de caducidad no figura en este archivo.':m==='B'?'La modalidad B permite optar a un nivel superior. Si no se mejora, la participación por B no renueva por sí sola el certificado.':m==='C'?'La modalidad C corresponde a la renovación del nivel. No requiere autoevaluación ni visita técnica.':canImprove?'Puedes mantener el trabajo del Plan Digital o presentarte voluntariamente por modalidad B para optar a un nivel superior.':'Puedes mantener actualizado y desarrollar el Plan Digital. El nivel 5 es el máximo, por lo que no corresponde optar a una mejora por modalidad B.';
let tasks=!applying?['No se prevé solicitud obligatoria en esta convocatoria según el listado.','Mantener actualizado y desarrollar el Plan Digital del centro.']:['La dirección debe presentar la solicitud en AEDO del 28 de septiembre al 23 de octubre de 2026, ambos inclusive, indicando la modalidad '+m+'.'];if(applying&&(m==='A'||m==='B'))tasks.push('Preparar el Plan Digital actualizado.','Realizar la autoevaluación del 3 al 27 de noviembre de 2026.','Recibir la visita del equipo técnico y aportar las evidencias correspondientes.');if(participating&&m==='C')tasks.push('Tramitar la renovación por modalidad C.','No realizar autoevaluación ni recibir visita técnica por esta modalidad.');
detail.innerHTML='<span class="badge '+(!participating?'no':'')+'">'+(participating?'Participación prevista · '+esc(c.mode):'Sin participación obligatoria')+'</span><h2>'+esc(c.name)+'</h2><p class="town">'+esc(c.town)+' · Código: '+esc(c.code)+' · Nivel actual: '+esc(c.level)+'</p><div class="fact"><strong>'+title+'</strong>'+why+'</div>'+(c.mode==='B/C'?'<h3>Elige el objetivo del centro</h3><p>El listado permite B o C. La respuesta cambia según la opción elegida.</p><div class="choices"><button class="choice" data-mode="C" aria-pressed="'+(choice==='C')+'">C · Renovar el nivel</button><button class="choice" data-mode="B" aria-pressed="'+(choice==='B')+'">B · Mejorar el nivel</button></div>':'')+(canImprove?'<h3>Participación voluntaria</h3><p>Tu centro puede optar a mejorar su nivel por modalidad B.</p><div class="choices"><button class="choice" data-mode="C" aria-pressed="'+(!voluntaryB)+'">No presentarse este curso</button><button class="choice" data-mode="B" aria-pressed="'+voluntaryB+'">B · Mejorar el nivel voluntariamente</button></div>':'')+'<h3>'+(applying?'Modalidad '+m+(voluntaryB?' · Voluntaria':''):'¿Qué hacer este curso?')+'</h3><p>'+explanation+'</p><ol>'+tasks.map(t=>'<li>'+t+'</li>').join('')+'</ol><div class="actions">'+(applying?'<a href="https://aplicaciones.educa.jcyl.es/AEDO/login/1706_1634" target="_blank" rel="noopener">Solicitud en AEDO</a>':'')+'<a href="https://neligarfer-wq.github.io/codice-tic/web-codice.html" target="_blank" rel="noopener">Consultar la guía</a></div>';detail.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{choice=b.dataset.mode;render();});}
query.addEventListener('input',()=>{results();const q=query.value.trim();const exact=CENTERS.find(c=>c.code===q);if(exact)select(exact.id);});results();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'consultar_centros_codice',description:'Busca centros por nombre o código y muestra la ficha cuando existe una coincidencia única para 2026/2027.',inputSchema:{type:'object',properties:{consulta:{type:'string'}},required:['consulta'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input.consulta!=='string'||!input.consulta.trim())throw new Error('Indica un nombre o código de centro.');query.value=input.consulta;results();const list=search(input.consulta);if(list.length===1)select(list[0].id);return list.map(c=>({codigo:c.code,nombre:c.name,localidad:c.town,nivel:c.level,participa:c.participates,modalidad:c.mode,curso:'2026/2027'}));}})).catch(()=>{});}catch{}}
